version: '2'
services:
  jupyter-lab:
    container_name: tensorflow_amplicon_gpt
    build: .
    ports:
      - "8888:8888"
    volumes:
      - "./:/amplicon_gpt"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]